### ISSUE TITLE
Crawlers: Check for duplicate file names

### ISSUE THREAD

**Issue by mathiaszinnen** [Odeuropa/wp2-annotations#3]
we could already check for duplicate file-names in the crawling if you (optionally) pass a metadata csv, and then skip the files for which the file names are already in

we do have a metadata file which contains all the images that have already been downloaded. If we could pass this file to the crawler as an argument, we could find out which images are already in our collection. Having this information we could then put them in a separate "duplicate images" folder, so we do not have them twice in our annotations

**Comment by AzharSindhi** [comment]
Done in the commit: https://github.com/mathiaszinnen/crawlerinhos/commit/4d3a5c08be12660047b250e9f0a316926266c686. Please suggest changes if any.
