### ISSUE TITLE
Crawlers: adapt collection specific csv file name to keyword

### ISSUE THREAD

**Issue by mathiaszinnen** [Odeuropa/wp2-annotations#4]
the collection-specific metadata csvs still have the Pomander in it, where it should be the keyword searched for, e.g. "chimney". Can you try finding the place in the code where this is done and adapt it to the current keyword?

**Comment by AzharSindhi** [comment]
Done in the commit: https://github.com/mathiaszinnen/crawlerinhos/commit/dbf98a678ed90084db829930d458aec6dbf88169. Please suggest changes if any :)
